version: "3"
services:
 #Grafana     
  grafana:
    image: grafana/grafana:latest
    container_name: grafana  
    build:
      context: ./Grafana
      dockerfile: dockerfile
      #restart: unless-stopped
      #user: "0"
    ports:
      - 3001:3000
    env_file:
      - ./grafana/grafana.env
    volumes:
      - .\Grafana\data:/var/lib/grafana
      - .\Grafana\log:/var/log/grafana
        #- c:/Docker/Iot/Grafaba/config:/etc/grafana/grafana.ini
  
  #Mosquitto
  Mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    build:
        context: ./mosquitto
        dockerfile: dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"
    #env_file:
    #  -
    volumes:
      - .\mosquitto\config:/mosquitto/config
      #- .\mosquitto\config\mosquitto.conf:/mosquitto/config/mosquitto.conf  -works in windows10
      - .\mosquitto\data:/mosquitto/data
      - .\mosquitto\log:/mosquitto/log
  #NodeRed    
  NodeRed:
    image: nodered/node-red:latest
    container_name: NodeRed
    build:
      context: ./NodeRed
      dockerfile: dockerfile
    ports:
      - "1880:1880"
    env_file:
      - ./nodered/nodered.env
    volumes:
      - .\nodered\data:/data

